apiVersion: apps/v1
kind: Deployment
metadata:
  name: osie-bootloader
spec:
  replicas: 1
  selector:
    matchLabels:
      tinkerbell/component: osie-bootloader
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tinkerbell/component: osie-bootloader
    spec:
      containers:
        - image: nginx:alpine
          name: osie-bootloader
          ports:
            - containerPort: 80
          tty: true
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: webroot
      restartPolicy: Always
      volumes:
        - name: webroot
          hostPath:
            path: /abhnvp/sandbox/deploy/compose/state/webroot