apiVersion: v1
kind: Service
metadata:
  name: boots-service-udp
spec:
  ports:
  - name: dhcp
    port: 67
    targetPort: 67
    protocol: UDP
  - name: tftp
    port: 69
    targetPort: 69
    protocol: UDP
  selector:
    io.kompose.service: boots
  type: LoadBalancer
  loadBalancerIP: 194.17.0.15