apiVersion: v1
kind: Service
metadata:
  name: tink-server
  labels:
    tinkerbell/component: tink-server
spec:
  ports:
    - name: "42113"
      port: 42113
      targetPort: 42113
    - name: "42114"
      port: 42114
      targetPort: 42114
  selector:
    tinkerbell/component: tink-server
  type: LoadBalancer
  loadBalancerIP: 194.17.0.15
